version: '2'
volumes:
  db-data: null
  app-env: null
services:

  api:
#    image: bluestreak/api:travis-12
    build:
      context: ./graphql-api
    environment:
      MAGE_HOST: http://mage
      MAGE_ADMIN_USERNAME: shakyshane
      MAGE_ADMIN_PASSWORD: 7*{4L*}49p3.Q&9
    ports:
      - '5000:8080'
    links:
      - entry

  entry:
    image: bluestreak/entry:3
#    build:
#      context: ./entry
    volumes_from:
      - php
    depends_on:
      - php

  php:
    image: bluestreak/magento:travis-17
#    build:
#      context: ./magento
    working_dir: /var/www
#    volumes:
#      - ./magento/app/code:/var/www/app/code
#      - ./magento/app/design:/var/www/app/design
    ports:
      - '9000'
    depends_on:
      - db
    environment:
      - HTTPS=on
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker

      - MAGE_HOST=https://shop.pwa.m2
      - MAGE_ADMIN_USER=admin
      - MAGE_ADMIN_PASS=password123

      - PHP_MEMORY_LIMIT=3G
      - VIRTUAL_HOST=https://shop.pwa.m2

  db:
    image: 'mysql:5.6'
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306'
    restart: unless-stopped

  redis:
    image: 'redis:3-alpine'
    ports:
      - '6379'

  caddy:
    build:
      context: ./pwa-fe
#    image: dockercloud/haproxy
    links:
      - entry
      - api
    ports:
      - '80:80'
      - '443:443'

